# Generated by Django 5.2.6 on 2025-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show your profile to others.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_on_comment',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone comments on your post.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_on_like',
            field=models.BooleanField(default=True, help_text='Receive notifications when someone likes your post.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', help_text='Who can see your posts and profile.', max_length=10),
        ),
    ]
